<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>translator</title>
<style>
textarea {
    width: 800px;
    height: 120px;
    margin: 4px;
}
</style>
<script src="http://code.jquery.com/jquery-1.7.2.min.js"></script>
</head>
<body>
    <form>
        <textarea name="text"><?= htmlspecialchars($text) ?></textarea><br />
        <textarea><?= htmlspecialchars($result) ?></textarea><br />
        <input type="submit" name="en" value="英→和"  />
        <input type="submit" name="ja" value="和→英"  />
    </form>
    
    <hr />
    <a href="http://www.microsofttranslator.com/dev/">http://www.microsofttranslator.com/dev/</a>
</body>
</html>

